Fix login
the-bugs/medcheck-backend-js pull request #22
Opened 2023-11-15 19:24 UTC by devruso

2023-11-15 22:40 UTC, matheusvictor requested changes

2023-11-15 22:40 UTC, matheusvictor commented on api/controllers/AuthController.js
> -            const usuario = await database.Usuario.unscoped().findOne({ where: { email } });
Por que a remoção?

2023-11-16 00:11 UTC, devruso commented on api/controllers/AuthController.js
> -            const usuario = await database.Usuario.unscoped().findOne({ where: { email } });
A função "unscoped" retira escopos padrão dos modelos que são utilizadas, nesse caso usuário. No modelo usuário tem o escopo de excluir o envio da senha. Não vi necessidade de enviar a senha na requisição se podemos acessar diretamente no banco de dados.

2023-11-16 01:06 UTC, matheusvictor approved these changes

2023-11-16 01:06 UTC, merged